version: '3'
services: 
  apache-php:
    build:
      context: ./apache-php
    ports:
      - 80:80
    volumes:
      - ./www:/var/www/html
    networks:
      - localSite
    restart: unless-stopped
  # Database
  mariadb:
    image: mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'no'
      MYSQL_ROOT_PASSWORD: 'ChangeMe!FIXME'
      MYSQL_INITDB_SKIP_TZINFO: 1
    networks:
      - localSite
    restart: unless-stopped
  # phpmyadmin
  phpmyadmin:
    depends_on:
      - mariadb
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    networks:
      - localSite
    restart: unless-stopped
    environment:
      PMA_HOST: mariadb
      MYSQL_ROOT_PASSWORD: 'ChangeMe!FIXME'
networks:
  localSite:
volumes:
  mariadb_data:
